### ISSUE TITLE
do not resume the socket

### ISSUE THREAD

**Issue by mcollina** [lolo32/fastify-http2https#2]
I've seen that the socket is manually resumed. Is this needed? I don't think it should be, as it might cause some issues with backpressure and stuff. Maybe it should be emitted in the next tick?

**Comment by lolo32** [comment]
Hi,
It's manually paused, so I need to resume it manually, the server cannot resume paused socket.
I take care to resume it at next tick, but only the first time that I pass the flow to the HTTP or HTTPS/2 server, I never do it again.

If it's a problem, please could you let me see some cone that could cause problem, or a link to a page?

**Comment by mcollina** [comment]
My bad, I didn't see the manual pause.
